export const categories = ['All', 'Beef', 'Lamb', 'Chicken', 'Smallgoods', 'Jerky & Cured'];

export const products = [
  {
    id: 1,
    name: 'Beef Sausages',
    category: 'Beef',
    description: 'Juicy, seasoned beef sausages made from premium cuts. Perfect for the BBQ or pan-fry.',
    price: '$12.99 / kg',
    emoji: '🌭',
    featured: true,
  },
  {
    id: 2,
    name: 'Lamb Chops',
    category: 'Lamb',
    description: 'Tender lamb chops from free-range lambs. Rich flavour, perfect for grilling.',
    price: '$22.99 / kg',
    emoji: '🍖',
    featured: true,
  },
  {
    id: 3,
    name: 'Chicken Wings',
    category: 'Chicken',
    description: 'Fresh chicken wings, great for marinating or frying. Buy in bulk and save.',
    price: '$8.99 / kg',
    emoji: '🍗',
    featured: true,
  },
  {
    id: 4,
    name: 'Beef Jerky',
    category: 'Jerky & Cured',
    description: 'House-made beef jerky with a smoky, sweet marinade. A fan favourite snack.',
    price: '$34.99 / kg',
    emoji: '🥩',
    featured: true,
  },
  {
    id: 5,
    name: 'Lamb Mince',
    category: 'Lamb',
    description: 'Freshly minced lamb shoulder. Perfect for kebabs, burgers, or meatballs.',
    price: '$14.99 / kg',
    emoji: '🫙',
    featured: false,
  },
  {
    id: 6,
    name: 'Chicken Breast Fillets',
    category: 'Chicken',
    description: 'Lean chicken breast fillets, skinless and boneless. Ready to cook.',
    price: '$13.99 / kg',
    emoji: '🍗',
    featured: false,
  },
  {
    id: 7,
    name: 'Beef Salami',
    category: 'Smallgoods',
    description: 'Traditional-style beef salami, sliced thin. A deli classic.',
    price: '$29.99 / kg',
    emoji: '🥩',
    featured: false,
  },
  {
    id: 8,
    name: 'Beef Mince',
    category: 'Beef',
    description: 'Premium quality beef mince, ideal for bolognese, burgers, and more.',
    price: '$11.99 / kg',
    emoji: '🥩',
    featured: false,
  },
  {
    id: 9,
    name: 'Lamb Shank',
    category: 'Lamb',
    description: 'Slow-cook lamb shanks that fall off the bone. A winter warmer favourite.',
    price: '$18.99 / kg',
    emoji: '🍖',
    featured: false,
  },
  {
    id: 10,
    name: 'Chicken Thigh Fillets',
    category: 'Chicken',
    description: 'Juicy boneless chicken thigh fillets. More flavour than breast.',
    price: '$10.99 / kg',
    emoji: '🍗',
    featured: false,
  },
  {
    id: 11,
    name: 'Beef Pastrami',
    category: 'Jerky & Cured',
    description: 'Seasoned and smoked beef pastrami. Perfect for sandwiches.',
    price: '$27.99 / kg',
    emoji: '🥩',
    featured: false,
  },
  {
    id: 12,
    name: 'Lamb Sausages',
    category: 'Smallgoods',
    description: 'Herbed lamb sausages, great on the BBQ or with roasted veg.',
    price: '$14.99 / kg',
    emoji: '🌭',
    featured: false,
  },
];
